baseURL = "https://zoe-maternidade.netlify.app/"
languageCode = "pt-br"
title = "Meu Site de Maternidade"
theme = "github.com/theNewDynamic/gohugo-theme-ananke" # <<< A LINHA CORRIGIDA

[module]
  [module.hugoVersion]
    extended = false
    min = "0.110.0"
