baseURL = "https://zoe-maternidade.netlify.app/"
languageCode = "pt-br"
title = "Meu Site de Maternidade"
theme = "github.com/apvarun/blist-hugo-theme"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.110.0"
